# SEO
title: "Randm's Ramblings"
author: 
  name: "randm"
  email: "samuel.bmc@proton.me"
url: "https://randm.website"
baseurl: ""
timezone: "America/Denver"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-sitemap

include:
  - tags

exclude:
  - build-site.sh

# RSS feeds
feed_items: 20
feed:
  posts_limit: 20
  tags: 
    path: "feeds/"